#' Construct a \code{data.table} object containing ATAC-seq peaks data
#'
#'
#' @title contrastDT
#' @param contrastList a list; the list of contrasts to compare
#' @param contrastMatrix a matrix; the matrix of contrasts generated by \code{makeContrasts} from \code{edgeR}
#' @return a \code{data.table} object
#' @import data.table
#' @export
#' @author Firas Sadiyah


contrastDT <- function(contrastList, contrastMatrix) {

    first.LRT <- glmLRT(y$fit, contrast = contrastMatrix[, contrastList[[1]]])
    first.TOP <- topTags(first.LRT, n = nrow(first.LRT), sort.by = "none", adjust.method = "BH")
    # construct the data.table for the contrast
    DT = data.table(as.data.frame(first.TOP))
    DT[, peaks := rownames(first.TOP$table)]
    DT[, peaks := as.numeric(peaks)]
    setcolorder(DT, c("peaks", "LR", "PValue", "logCPM", "logFC", "FDR"))

    # change names of the first contrast
    setnames(DT, "PValue", paste0(contrastList[[1]], "_PValue"))
    setnames(DT, "logCPM", paste0(contrastList[[1]], "_logCPM"))
    setnames(DT, "logFC", paste0(contrastList[[1]], "_LFC"))
    setnames(DT, "FDR", paste0(contrastList[[1]], "_FDR"))

    for (contrast in contrastList[2:length(contrastList)]) {
        contrast.LRT <- glmLRT(y$fit, contrast = contrastMatrix[, contrast])
        contrast.TOP <- topTags(contrast.LRT, n = nrow(contrast.LRT), sort.by = "none", adjust.method = "BH")
        DT[, paste0(contrast, "_PValue") := contrast.TOP$table$PValue]
        DT[, paste0(contrast, "_logCPM") := contrast.TOP$table$logCPM]
        DT[, paste0(contrast, "_LFC")    := contrast.TOP$table$logFC]
        DT[, paste0(contrast, "_FDR")    := contrast.TOP$table$FDR]
        }

    for (contrast in contrastList[seq_along(contrastList)]) {
        paste0(contrast, "_DAR") -> contrast_DAR
        paste0(contrast, "_FDR") -> contrast_FDR
        paste0(contrast, "_LFC") -> contrast_LFC
        paste0(contrast, "_UP")  -> contrast_UP
        paste0(contrast, "_DN")  -> contrast_DN
        DT[, substitute(contrast_DAR) := "Unchanged"]
        DT[DT[[contrast_FDR]] < parList$FDR & DT[[contrast_LFC]] >  parList$LFC, substitute(contrast_DAR) := "Opened"]
        DT[DT[[contrast_FDR]] < parList$FDR & DT[[contrast_LFC]] < -parList$LFC, substitute(contrast_DAR) := "Closed"]
        }

    setkey(DT, peaks)

    DT <- merge(DT, atacPeaks$logCPM, by = "peaks")
    DT <- merge(DT, atacPeaks$annt,   by = "peaks")

    DT_UP <- list()
    DT_DN <- list()
    for (contrast in contrastList[seq_along(contrastList)]) {
        paste0(contrast, "_DAR") -> contrast_DAR
        paste0(contrast, "_FDR") -> contrast_FDR
        paste0(contrast, "_LFC") -> contrast_LFC
        paste0(contrast, "_UP")  -> contrast_UP
        paste0(contrast, "_DN")  -> contrast_DN
        contrast.UP <- subset(DT, DT[[contrast_FDR]] < parList$FDR & DT[[contrast_LFC]] > parList$LFC)
        DT_UP[contrast_UP] <- list(contrast.UP)
        contrast.DN <- subset(DT, DT[[contrast_FDR]] < parList$FDR & DT[[contrast_LFC]] < -parList$LFC)
        DT_DN[contrast_DN] <- list(contrast.DN)
        }

    return(list("DT" = DT, "UP" = DT_UP, "DN" = DT_DN))
}
