#' Read .motif files generated by HOMER motif analysis
#'
#'
#' @title readSeqLogo
#' @param resPath a string; the path where .motif files are stored
#' @param n an integer; the number of .motif files to read
#' @return a list of motifs
#' @import readr
#' @export
#' @author Firas Sadiyah


readSeqLogo <- function(resPath, n) {
    seqLogoList <- list()
    for (i in seq_along(1:y)) {
        seqLogo_i <- read_tsv(paste0(z, "/knownResults/known", i, ".motif"),
            skip = 1, col_types = cols())
        seqName_i <- read_tsv(paste0(z, "/knownResults/known", i, ".motif"),
            n_max = 1, col_types = cols(), col_names = FALSE)
        seqName_i <- toupper(gsub("\\(.*", "", seqName_i[[2]]))
        seqLogo_i <- t(as.matrix(seqLogo_i))
        rownames(seqLogo_i) <- c("A", "C", "G", "T")
        seqLogoList[[seqName_i]] <- seqLogo_i
    }
    return(seqLogoList)
}


#' Plot a list of motifs as sequence logo
#'
#'
#' @title plotSeqLogo
#' @param motifList a list; the list of motifs generated by readSeqLogo()
#' @param n an integer; the number of motifs to plot
#' @return ggplot2 object
#' @import ggseqlogo
#' @import ggplot2
#' @export
#' @author Firas Sadiyah


plotSeqLogo <- function(motifList, n = 1) {
    ggseqlogo::ggseqlogo(motifList, method = "p", ncol = n) +
        themeFX() +
        theme(strip.background = element_blank())
}
